fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: "git://github.com/ripienaar/puppet-concat.git"
    mysql: 
      repo: "git@github.com:puppetlabs/puppetlabs-mysql.git"
      ref: '1.0.0'
    apache: 
      repo: "git@github.com:puppetlabs/puppetlabs-apache.git"
      ref: '0.8.1'
    #firewall: "git://github.com/puppetlabs/puppetlabs-firewall.git"
  symlinks:
    wordpress: "#{source_dir}"
