name    'puppet-wordpress'
version '0.0.6'
source 'https://github.com/wolfspyre/puppet-wordpress'
license 'Apache License, Version 2.0'
summary 'Installs wordpress and configures it'
description 'This module manages a wordpress setup. It will support standalone (self contained), standalone, or app-only modes'
project_page 'https://github.com/wolfspyre/puppet-wordpress'
